### ISSUE TITLE
Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mhdawson** [appsody/docs#41]
The links for `README` and `development environment` in 

>Check out this README to learn about the Appsody source base and setting up your development environment.

within https://github.com/appsody/docs/blob/master/CONTRIBUTING.md both 404 for me.

**Comment by mhamwala** [comment]
Thanks for raising this issue @mhdawson! the following links should point to:

[README](https://github.com/appsody/docs/blob/master/README.md)
[development environment](https://github.com/appsody/docs/blob/master/docs/using-appsody/local-development.md)
