### ISSUE TITLE
Links to stack-structures 404s on website

### ISSUE THREAD

**Issue by mhdawson** [appsody/docs#49]
The 2 links to stack-structures 404s on the website in:

https://appsody.dev/docs/stacks/create-or-modify

One seems to be missing the /docs/stacks that the other link has, will submit a PR to fix that.  But the main problem seems to be that in the deployed side the link that does work in the overview.md is misspelled as https://appsody.dev/docs/stacks/stack-stucture (missing r).  But that looks to be fixed in the repo, so maybe an update the site is needed or there is some problem in conversation that is introducing the misspelling of the name

**Comment by mhdawson** [comment]
Looks like this will probably fix the problem with the path https://github.com/appsody/docs/pull/47

**Comment by mhamwala** [comment]
@mhdawson Yep good catch! thanks for the PR, the website will be updated shortly!
